import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { RoutingPolicyFields, RoutingStrategyOptions, routingPolicyInput, RoutingPolicyEvidence } from "./RoutingPolicyFields";

type API = <T = any>(path: string, method?: string, body?: unknown) => Promise<T>;
type Props = { api: API; sources: any[]; clientKeys:any[]; page: string; selectedId?: string; onChanged:()=>Promise<void> };
export function ConsoleModules({ api, sources, clientKeys, page, selectedId, onChanged }: Props) {
  const [models, setModels] = useState<any[]>([]), [routes, setRoutes] = useState<any[]>([]), [aliases, setAliases] = useState<any[]>([]);
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [pending, setPending] = useState<string[]>([]);
  const [selected, setSelected] = useState<string[]>([]), [preview, setPreview] = useState<any>(null);
  const [edits,setEdits]=useState<Record<string,{version:number;formVersion:number;base:any;readError?:string}>>({});
  const [loading,setLoading]=useState(true);
  const revision=useRef(0),mounted=useRef(true),running=useRef(new Set<string>());
  const focusRequests=useRef<Array<{trigger:HTMLElement|null;focusID?:string}>>([]);
  // Restore only after React commits the enabled replacement of a keyed form.
  useLayoutEffect(() => {
    const requests=focusRequests.current;focusRequests.current=[];
    for(const {trigger,focusID} of requests){
      if(document.activeElement!==document.body&&document.activeElement!==trigger)continue;
      (trigger?.isConnected?trigger:focusID?document.getElementById(focusID):null)?.focus();
    }
  }, [pending]);
  async function load() {
    const generation=++revision.current;setLoading(true);setError("");
    const results = await Promise.allSettled([api("models"), api("routes"), api("model-aliases")]);
    if(!mounted.current||generation!==revision.current)return;setLoading(false);
    if (results[0].status === "fulfilled") {const items=results[0].value.items;setModels(old=>items.map((v:any)=>{const previous=old.find(m=>m.id===v.id);return previous&&previous.version>v.version?previous:v}));}
    if (results[1].status === "fulfilled") {const items=results[1].value.items;setRoutes(old=>items.map((v:any)=>{const previous=old.find(r=>r.id===v.id);return previous&&previous.version>v.version?previous:v}));}
    if (results[2].status === "fulfilled") setAliases(results[2].value.items);
    const failures = results.filter((v): v is PromiseRejectedResult => v.status === "rejected");
    if (failures.length) setError(failures.map((v) => v.reason.message).join("；"));
  }
  useEffect(() => { let active = true;mounted.current=true;revision.current++; load().catch((e) => { if (active) setError(e.message); }); return () => { active = false;mounted.current=false;revision.current++; }; }, [page]);
  async function run(id: string, fn: () => Promise<void>) { if(running.current.has(id))return;const trigger=document.activeElement instanceof HTMLElement?document.activeElement:null,focusID=trigger?.id;running.current.add(id);setPending([...running.current]); setError(""); setNotice(""); try { await fn(); await Promise.all([load(),onChanged()]); } catch (e) { if(mounted.current)setError((e as Error).message); } finally { running.current.delete(id);if(mounted.current){focusRequests.current.push({trigger,focusID});setPending([...running.current])} } }
  async function saveEdit(kind:"models"|"routes",entity:any,patch:unknown,after?:()=>Promise<void>){
    const edit=edits[entity.id]??{version:entity.version,formVersion:entity.version,base:entity};
    let saved=false;
    try{await api(`${kind}/${entity.id}`,"PATCH",{...(patch as object),version:edit.version});saved=true;if(after)await after()}
    catch(error){
      if(mounted.current)setEdits(old=>({...old,[entity.id]:edit}));
      if(saved&&after&&mounted.current)setNotice("模型元数据已保存，价格更新未完成；本地输入已保留，请比较当前设置后重新提交。");
      if(saved||(error as Error&{status?:number}).status===409){
        try{const latest=await api(`${kind}/${entity.id}`);if(mounted.current)(kind==="models"?setModels:setRoutes)(old=>old.map(v=>v.id===entity.id&&latest.version>=v.version?latest:v))}
        catch(readError){if(mounted.current)setEdits(old=>({...old,[entity.id]:{...edit,readError:`无法读取当前配置：${(readError as Error).message}`}}))}
      }
      throw error;
    }
    if(mounted.current)setEdits(old=>{const next={...old};delete next[entity.id];return next});
  }
  async function discover(source: any) {
    await run(source.id, async () => { let operation = await api(`sources/${source.id}/models/discover`, "POST", {});
      let delay=1000;while (operation.state === "running"&&mounted.current) { await new Promise((resolve) => setTimeout(resolve,delay));if(!mounted.current)return; operation = await api(`operations/${operation.id}`);delay=Math.min(delay*2,8000); }
      if (operation.state !== "succeeded") throw new Error(operation.error || "获取模型未完成，旧目录保留");
      setNotice("模型目录已获取；勾选启用后才可路由，真实调用仍需验证。");
    });
  }
  return <>
    {loading&&<p role="status">正在读取配置…</p>}
    {!loading&&error&&<button onClick={()=>void load()}>重新读取配置</button>}
    {error && <div id="catalog-error" role="alert" className="error">{error}</div>}{notice && <div role="status" className="notice">{notice}</div>}
    {page === "模型" && <>
      <section className="panel"><h2>来源模型目录</h2><p>发现、手工配置、可路由和真实验证分别记录。未知上下文和价格保持未知。</p>
        {sources.map((s) => <div className="tool-row" key={s.id}><div><strong>{s.name}</strong><span>{s.native_protocol || "responses"} · {s.models.length} 个已启用模型</span></div><button disabled={pending.includes(s.id)} onClick={() => discover(s)}>获取模型</button></div>)}
        {!sources.length && <p>先在来源页添加一个来源。</p>}
      </section>
      <section className="panel"><h2>手工添加模型</h2><form className="inline-form" onSubmit={(e) => { e.preventDefault(); const element=e.currentTarget, form = new FormData(element); run("add", async () => { await api("models", "POST", { source_id: form.get("source"), upstream_model: form.get("model"), display_name: form.get("display_name") }); element.reset();element.dataset.dirty="false";setNotice("已添加为手工模型，尚未验证。"); }); }}>
        <select name="source" aria-label="模型来源" required><option value="">选择来源</option>{sources.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select>
        <input name="model" aria-label="上游模型 ID" required placeholder="上游模型 ID"/><input name="display_name" aria-label="模型显示名" placeholder="显示名（可选）"/><button disabled={pending.includes("add")}>添加模型</button>
      </form></section>
      <section className="panel"><h2>模型与价格</h2>{!loading&&!error&&!models.length && <p>还没有模型，可以获取目录或手工添加。</p>}{models.filter(m => !selectedId || m.id === selectedId).map((m) => {const edit=edits[m.id],model=edit?.base??m;return <article className="source-card" key={m.id}>
        <div className="section-title"><h3>{m.display_name}</h3><span className="badge muted">{m.discovery === "manual" ? "手工配置" : m.discovery === "stale" ? "目录已过期" : "已发现"} · {m.verification === "passed" ? "已验证" : m.verification === "failed" ? "验证失败" : m.verification === "stale" ? "验证已过期" : "尚未验证"}</span></div><code>{m.upstream_model}</code><p>{sources.find((s) => s.id === m.source_id)?.name} · 上下文 {m.context_limit ?? "未知"} · 输出上限 {m.max_output ?? "未知"}</p>
        <button disabled={pending.includes(m.id)} onClick={() => run(m.id, async () => { await api(`models/${m.id}`, "PATCH", { version: m.version, enabled: !m.enabled }); })}>{m.enabled ? "停用模型" : "启用模型"}</button>
        <button disabled={pending.includes(m.id)} onClick={()=>run(m.id,async()=>{const source=sources.find(s=>s.id===m.source_id);let op=await api(`models/${m.id}/verify`,"POST",{source_id:m.source_id,expected_source_generation:source.binding_generation,protocol:"responses",features:[source.kind==="codex_subscription"?"text_sse":"text_json"]});let delay=1000;while(op.state==="running"&&mounted.current){await new Promise(r=>setTimeout(r,delay));if(!mounted.current)return;op=await api(`operations/${op.id}`);delay=Math.min(delay*2,8000)}if(op.state!=="succeeded")throw new Error(op.error||"验证未完成");setNotice(op.result?.passed?"本次文本调用已验证，其余能力仍需单独验证。":"验证未通过，请查看请求记录。")})}>验证文本（会产生上游调用）</button>
        {sources.find(s=>s.id===m.source_id)?.kind==="api_key"&&sources.find(s=>s.id===m.source_id)?.native_protocol==="responses"&&sources.find(s=>s.id===m.source_id)?.native_operations?.includes("background")&&<details><summary>验证后台 Responses（会产生上游调用）</summary><p>选用现有 Key 的权限、并发与预算，创建一次持久任务并观察到真实终态。超时或未知不算验证通过。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(m.id,async()=>{const source=sources.find(s=>s.id===m.source_id);let op=await api(`models/${m.id}/verify`,"POST",{expected_source_generation:source.binding_generation,source_id:source.id,protocol:"responses",features:["background"],client_key_id:f.get("key")});let delay=1000;while(op.state==="running"&&mounted.current){await new Promise(r=>setTimeout(r,delay));if(!mounted.current)return;op=await api(`operations/${op.id}`);delay=Math.min(delay*2,8000)}if(op.state!=="succeeded")throw new Error(op.error||"验证未完成");setNotice(op.result?.passed?"后台能力已通过真实创建与终态观察。":"后台验证未通过，未决任务与账务保留。")})}}><label>验证使用的 Key<select name="key" required><option value="">选择直接绑定此来源的 Key</option>{clientKeys.filter(k=>k.source_id===m.source_id&&!k.revoked).map(k=><option value={k.id} key={k.id}>{k.name}</option>)}</select></label><button disabled={pending.includes(m.id)}>验证后台任务</button></form></details>}
        <details><summary>配置价格与元数据</summary><form data-dirty={!!edit} aria-describedby={error?"catalog-error":undefined} key={edit?.formVersion??m.version} onChange={()=>setEdits(old=>old[m.id]?old:{...old,[m.id]:{version:m.version,formVersion:m.version,base:m}})} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); run(m.id, async () => { await saveEdit("models",m,{ context_limit:f.get("context")?Number(f.get("context")):null, max_output:f.get("max")?Number(f.get("max")):null, modalities:String(f.get("modalities")||"").split(",").map(v=>v.trim()).filter(Boolean), features:String(f.get("features")||"").split(",").map(v=>v.trim()).filter(Boolean), metadata_reason:f.get("reason"), native_server_tools:String(f.get("server_tools")||"").split(",").map(v=>v.trim()).filter(Boolean), opaque_history:f.get("opaque")==="on",adapter_version:f.get("adapter"),websocket_adapter:f.get("websocket"),websocket_warmup:f.get("warmup")==="on",websocket_steering:false },async()=>{if(f.get("input") && f.get("output")) await api("prices","POST",{model_id:m.id,currency:f.get("currency"),effective_at:new Date().toISOString(),units:[{dimension:"input_token",amount:f.get("input"),per:"1000000"},{dimension:"output_token",amount:f.get("output"),per:"1000000"},...(f.get("cached")?[{dimension:"cached_input_token",amount:f.get("cached"),per:"1000000"}]:[])],provenance:{kind:"manual",observed_at:new Date().toISOString()}});}); }); }}>
          <fieldset disabled={pending.includes(m.id)}>
          <label>上下文上限<input name="context" type="number" min="1" defaultValue={model.context_limit || ""}/></label><label>输出上限<input name="max" type="number" min="1" defaultValue={model.max_output || ""}/></label>
          <label>输入类型（逗号分隔）<input name="modalities" defaultValue={(model.modalities||[]).join(",")} placeholder="text,image"/></label><label>能力（逗号分隔）<input name="features" defaultValue={(model.features||[]).join(",")}/></label><label>元数据依据<input name="reason" required defaultValue={model.metadata_reason||""} placeholder="服务商文档或本次人工配置依据"/></label><label>原生服务端工具<input name="server_tools" defaultValue={(model.native_server_tools||[]).join(",")} placeholder="web_search；仅对应来源支持时可用"/></label><label><input name="opaque" type="checkbox" defaultChecked={model.opaque_history}/>允许已绑定的 opaque 历史</label><label>适配卡版本<input name="adapter" defaultValue={model.adapter_version||""}/></label><label>WebSocket 适配卡<select name="websocket" defaultValue={model.websocket_adapter||""}><option value="">关闭</option><option value="openai_responses_websocket_v1">OpenAI Responses v1</option><option value="codex_responses_websocket_0_158_0">Codex 0.158.0</option><option value="openai_realtime_websocket_v1">OpenAI Realtime v1</option></select></label><label><input name="warmup" type="checkbox" defaultChecked={model.websocket_warmup}/>公开 Responses 支持预热</label><label>币种<input name="currency" defaultValue={model.price?.currency || "USD"} pattern="[A-Z]{3}"/></label><label>每百万输入 token<input name="input" defaultValue={model.price?.input_per_million || ""}/></label><label>每百万输出 token<input name="output" defaultValue={model.price?.output_per_million || ""}/></label><label>每百万缓存读取 token<input name="cached" defaultValue={model.price?.cached_per_million || ""}/></label><button id={`model-${m.id}-save`} disabled={pending.includes(m.id)}>保存模型设置</button>
        </fieldset>
          {edit&&edit.version!==m.version&&<div role="region" aria-label="模型设置版本冲突" aria-live="polite"><p>编辑基于 v{edit.version}；当前 v{m.version}。本地输入已保留，请比较当前设置后重新提交。</p><p>当前上下文 {m.context_limit??"未知"}；输出上限 {m.max_output??"未知"}；输入类型 {JSON.stringify(m.modalities)}；能力 {JSON.stringify(m.features)}；依据 {m.metadata_reason||"未设置"}；原生工具 {JSON.stringify(m.native_server_tools)}；opaque {String(m.opaque_history)}；适配卡 {m.adapter_version||"未设置"}；WebSocket {m.websocket_adapter||"关闭"}；预热 {String(m.websocket_warmup)}；价格 {JSON.stringify(m.price)}。</p><button type="button" disabled={pending.includes(m.id)} onClick={()=>setEdits(old=>({...old,[m.id]:{...edit,version:m.version,readError:undefined}}))}>使用当前版本，保留模型输入</button><button type="button" disabled={pending.includes(m.id)} onClick={()=>setEdits(old=>{const next={...old};delete next[m.id];return next})}>放弃模型修改</button></div>}
          {edit?.readError&&<p role="alert" className="error">{edit.readError}；本地输入已保留。</p>}
        </form></details>
      </article>})}</section>
    </>}
    {page === "路由" && <>
      <section className="panel"><h2>创建路由</h2><form onSubmit={(e) => { e.preventDefault(); const element=e.currentTarget, f = new FormData(element); run("route", async () => { await api("routes", "POST", { name: f.get("name"), strategy: f.get("strategy"), max_attempts: Number(f.get("attempts") || 1), queue_limit:Number(f.get("queue")||0), queue_timeout_ms:Number(f.get("queue_timeout")||5000), ...routingPolicyInput(f), members: selected.map((id) => ({ model_id: id, priority: Number(f.get(`priority_${id}`) || 0), weight: Number(f.get(`weight_${id}`) || 1) })), allow_parameter_adjustment: f.get("adjustment") === "on", ...(f.get("concurrent") ? { max_concurrent: Number(f.get("concurrent")) } : {}) }); element.reset();element.dataset.dirty="false";setSelected([]); setNotice("路由已保存，添加公开模型别名后可绑定 Key。"); }); }}>
        <label>名称<input name="name" required/></label><label>策略<select name="strategy"><option value="priority">优先级</option><option value="weighted_round_robin">平滑加权轮询</option><RoutingStrategyOptions/></select></label><label>路由并发上限<input name="concurrent" type="number" min="1" placeholder="不设此层限制"/></label>
        <label>最多尝试次数<input name="attempts" type="number" min="1" max="3" defaultValue="1"/></label><label>等待队列容量<input name="queue" type="number" min="0" defaultValue="0"/></label><label>最长排队（毫秒）<input name="queue_timeout" type="number" min="1" defaultValue="5000"/></label><RoutingPolicyFields/><label><input name="adjustment" type="checkbox"/>允许来源已开启的订阅参数调整</label>
        {models.filter((m) => m.enabled).map((m) => <div className="inline-form" key={m.id}><label><input type="checkbox" checked={selected.includes(m.id)} onChange={(e) => setSelected((old) => e.target.checked ? [...old, m.id] : old.filter((id) => id !== m.id))}/>{sources.find((s) => s.id === m.source_id)?.name} / {m.upstream_model}</label><input name={`priority_${m.id}`} aria-label={`${m.upstream_model} 优先级`} type="number" defaultValue="0"/><input name={`weight_${m.id}`} aria-label={`${m.upstream_model} 权重`} type="number" min="1" defaultValue="1"/></div>)}
        <button disabled={pending.includes("route")}>创建路由</button>
      </form></section>
      <section className="panel"><h2>公开模型别名</h2><form className="inline-form" onSubmit={(e) => { e.preventDefault(); const element=e.currentTarget, f = new FormData(element); run("alias", async () => { await api("model-aliases", "POST", { public_model: f.get("alias"), route_id: f.get("route") });element.reset();element.dataset.dirty="false"; }); }}><input name="alias" aria-label="公开模型 ID" placeholder="例如 coding" required/><select name="route" aria-label="别名路由" required>{routes.map((r) => <option value={r.id} key={r.id}>{r.name}</option>)}</select><button disabled={pending.includes("alias") || !routes.length}>添加别名</button></form>
        {aliases.map((v) => <div className="tool-row" key={v.public_model}><code>{v.public_model}</code><select aria-label={`${v.public_model} 绑定路由`} disabled={pending.includes(v.public_model)} value={v.route_id} onChange={e=>run(v.public_model,async()=>{await api(`model-aliases/${encodeURIComponent(v.public_model)}`,"PATCH",{version:v.version,route_id:e.target.value})})}>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="text" disabled={pending.includes(v.public_model)} onClick={() => run(v.public_model, async () => { await api(`model-aliases/${encodeURIComponent(v.public_model)}`, "DELETE"); })}>删除别名</button></div>)}
      </section>
      <section className="panel"><h2>路由预览</h2>{!loading&&!error&&!routes.length&&<p>还没有路由，可以在上方创建空路由并添加成员。</p>}<p>只计算选择与排除原因，不调用上游、不消耗预算，也不推进轮询。</p>{routes.filter(route => !selectedId || route.id === selectedId).map((route) => {const edit=edits[route.id],value=edit?.base??route;return <div className="tool-row" key={route.id}><div><strong>{route.name}</strong><span>{route.members.length} 个成员 · {route.strategy} · 版本 {route.version}</span></div><button disabled={pending.includes(route.id) || !aliases.some((a) => a.route_id === route.id)} onClick={() => run(route.id, async () => { const alias = aliases.find((a) => a.route_id === route.id); setPreview(await api(`routes/${route.id}/preview`, "POST", { model: alias.public_model, protocol: "responses" })); })}>预览选择</button><details><summary>编辑路由</summary><form data-dirty={!!edit} aria-describedby={error?"catalog-error":undefined} key={edit?.formVersion??route.version} onChange={()=>setEdits(old=>old[route.id]?old:{...old,[route.id]:{version:route.version,formVersion:route.version,base:route}})} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(route.id,async()=>{await saveEdit("routes",route,{name:f.get("name"),enabled:f.get("enabled")==="on",strategy:f.get("strategy"),max_attempts:Number(f.get("attempts")),max_concurrent:f.get("concurrent")?Number(f.get("concurrent")):null,queue_limit:Number(f.get("queue")),queue_timeout_ms:Number(f.get("queue_timeout")),...routingPolicyInput(f),members:f.getAll("members").map(id=>({model_id:id,priority:Number(f.get(`priority_${id}`)||0),weight:Number(f.get(`weight_${id}`)||1)})),allow_parameter_adjustment:f.get("adjustment")==="on"})})}}>
          <fieldset disabled={pending.includes(route.id)}>
          <label>名称<input name="name" defaultValue={value.name} required/></label><label><input name="enabled" type="checkbox" defaultChecked={value.enabled}/>允许新请求</label><label>策略<select name="strategy" defaultValue={value.strategy}><option value="priority">优先级</option><option value="weighted_round_robin">平滑加权轮询</option><RoutingStrategyOptions/></select></label><label>路由并发<input name="concurrent" type="number" min="1" defaultValue={value.max_concurrent??""}/></label><label>最多尝试<input name="attempts" type="number" min="1" max="3" defaultValue={value.max_attempts}/></label><label>等待容量<input name="queue" type="number" min="0" defaultValue={value.queue_limit}/></label><label>排队毫秒<input name="queue_timeout" type="number" min="1" defaultValue={value.queue_timeout_ms}/></label><RoutingPolicyFields policy={value}/><label><input name="adjustment" type="checkbox" defaultChecked={value.allow_parameter_adjustment}/>允许已配置的参数调整</label>
          {models.map(m=>{const member=value.members.find((v:any)=>v.model_id===m.id);return <div key={m.id}><label><input name="members" type="checkbox" value={m.id} defaultChecked={!!member}/>{m.display_name}</label><label>优先级<input name={`priority_${m.id}`} type="number" defaultValue={member?.priority??0}/></label><label>权重<input name={`weight_${m.id}`} type="number" min="1" defaultValue={member?.weight??1}/></label></div>})}<button id={`route-${route.id}-save`} disabled={pending.includes(route.id)}>保存路由</button></fieldset>
          {edit&&edit.version!==route.version&&<div role="region" aria-label="路由设置版本冲突" aria-live="polite"><p>编辑基于 v{edit.version}；当前 v{route.version}。本地输入已保留，请比较当前设置后重新提交。</p><p>当前名称 {route.name}；启用 {String(route.enabled)}；策略 {route.strategy}；尝试 {route.max_attempts}；并发 {route.max_concurrent??"未设置"}；队列 {route.queue_limit}/{route.queue_timeout_ms}ms；参数调整 {String(route.allow_parameter_adjustment)}；成员 {JSON.stringify(route.members)}。</p><p>当前策略参数 {JSON.stringify({allow_cross_model:route.allow_cross_model,affinity_ttl_seconds:route.affinity_ttl_seconds,strict_context:route.strict_context})}。</p><button type="button" disabled={pending.includes(route.id)} onClick={()=>setEdits(old=>({...old,[route.id]:{...edit,version:route.version,readError:undefined}}))}>使用当前版本，保留路由输入</button><button type="button" disabled={pending.includes(route.id)} onClick={()=>setEdits(old=>{const next={...old};delete next[route.id];return next})}>放弃路由修改</button></div>}
          {edit?.readError&&<p role="alert" className="error">{edit.readError}；本地输入已保留。</p>}
        </form></details><button className="text" disabled={pending.includes(route.id)} onClick={() => run(route.id, async () => { await api(`routes/${route.id}`, "DELETE"); })}>删除路由</button></div>})}
        {preview?.policy?.candidates?.length > 0 && <RoutingPolicyEvidence snapshot={preview.policy}/>}
        {preview && <div><p>{preview.selected_candidate ? `选择 ${preview.selected_candidate.upstream_model}` : preview.error || "没有可用候选"}</p>{preview.candidates.map((c: any) => <p key={c.model_id}>{c.upstream_model} · {c.reason}</p>)}</div>}
      </section>
    </>}
  </>;
}
