import {useEffect,useState,type ReactNode} from "react";
type User={id:string;username:string;platform_admin:boolean;enabled:boolean;version:number};
type Tenant={id:string;name:string;enabled:boolean;version:number;role:string};
async function api(path:string,method="GET",body?:unknown){
 const r=await fetch(path,{method,credentials:"same-origin",redirect:"error",headers:body===undefined?{}:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();
 if(!r.ok)throw Object.assign(new Error(value.error?.message||`请求失败 ${r.status}`),{status:r.status});return value;
}
export function EnterpriseConsole({tenantID,renderAdmin}:{tenantID?:string;renderAdmin:()=>ReactNode}){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[tenants,setTenants]=useState<Tenant[]>([]),[users,setUsers]=useState<User[]>([]),[audit,setAudit]=useState<any[]>([]);
 const [name,setName]=useState(""),[newUser,setNewUser]=useState(""),[newPassword,setNewPassword]=useState(""),[platformAdmin,setPlatformAdmin]=useState(false);
 const [selectedTenant,setSelectedTenant]=useState(""),[selectedUser,setSelectedUser]=useState(""),[role,setRole]=useState("viewer"),[version,setVersion]=useState<number|null>(null),[report,setReport]=useState<any>(null);
 const [oldPassword,setOldPassword]=useState(""),[freshPassword,setFreshPassword]=useState("");
 async function refresh(current:User){
  const list=await api("/enterprise/tenants");setTenants(list.items);
  if(current.platform_admin){const [u,a]=await Promise.all([api("/enterprise/users"),api("/enterprise/audit")]);setUsers(u.items);setAudit(a.items)}
  const t=list.items.find((item:Tenant)=>item.id===tenantID);
  if(tenantID&&!t)throw new Error("没有此租户的访问权限。");
  if(t?.enabled&&t.role==="viewer"){const base=`/t/${t.id}/admin/`;const [usage,requests,budgets]=await Promise.all([api(base+"usage"),api(base+"requests?limit=50"),api(base+"budgets")]);setReport({usage,requests:requests.items,budgets:budgets.items})}
 }
 useEffect(()=>{let active=true;api("/enterprise/session").then(async u=>{if(active){setUser(u);await refresh(u)}}).catch(err=>{if(active&&err.status!==401)setError(err.message)}).finally(()=>{if(active)setReady(true)});return()=>{active=false}},[]);
 useEffect(()=>{setVersion(null);if(!selectedTenant||!selectedUser)return;let active=true;api(`/enterprise/tenants/${selectedTenant}/members/${selectedUser}`).then(value=>{if(active){setRole(value.role);setVersion(value.version)}}).catch(err=>{if(active){if(err.status===404)setVersion(0);else setError(err.message)}});return()=>{active=false}},[selectedTenant,selectedUser]);
 async function run(task:()=>Promise<void>){setBusy(true);setError("");setNotice("");try{await task()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 if(!ready)return <main className="login-shell"><h1>Cove 企业</h1><p role="status">正在读取会话…</p></main>;
 if(!user)return <main className="login-shell"><h1>Cove 企业登录</h1><p>使用企业管理员为你创建的账户。</p>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={e=>{e.preventDefault();void run(async()=>{const u=await api("/enterprise/session","POST",{username,password});setPassword("");setUser(u);await refresh(u)})}}><label>用户名<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label>密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?"正在登录…":"登录"}</button></form></main>;
 const tenant=tenants.find(t=>t.id===tenantID);
 return <><section className="enterprise-shell"><header><h1>Cove 企业{tenant?` · ${tenant.name}`:""}</h1><p>{user.username} · {user.platform_admin?"平台管理员":tenant?.role==="tenant_admin"?"租户管理员":"查看者"}</p><a href="/">企业目录</a> <button disabled={busy} onClick={()=>void run(async()=>{await api("/enterprise/session","DELETE");window.location.assign("/")})}>退出登录</button></header>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <details><summary>修改密码</summary><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api("/enterprise/password","POST",{current_password:oldPassword,new_password:freshPassword});setOldPassword("");setFreshPassword("");window.location.assign("/")})}}><label>当前密码<input type="password" autoComplete="current-password" required value={oldPassword} onChange={e=>setOldPassword(e.target.value)}/></label><label>新密码<input type="password" autoComplete="new-password" minLength={12} required value={freshPassword} onChange={e=>setFreshPassword(e.target.value)}/></label><button disabled={busy}>保存并重新登录</button></form></details>
 {!tenantID&&<><h2>租户</h2>{tenants.length===0&&<p>尚无租户。管理员创建后可分配成员。</p>}<ul>{tenants.map(t=><li key={t.id}>{t.enabled?<a href={`/t/${t.id}/`}>{t.name}</a>:<span>{t.name} · 已停用</span>} · {t.role==="tenant_admin"?"租户管理员":"查看者"}{user.platform_admin&&<button disabled={busy} onClick={()=>void run(async()=>{await api(`/enterprise/tenants/${t.id}`,"PATCH",{version:t.version,enabled:!t.enabled});await refresh(user)})}>{t.enabled?"停用租户":"启用租户"}</button>}</li>)}</ul></>}
 {!tenantID&&user.platform_admin&&<><section><h2>创建租户</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api("/enterprise/tenants","POST",{name});setName("");await refresh(user)})}}><label>租户名称<input required value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy}>创建租户</button></form></section>
 <section><h2>用户</h2><ul>{users.map(u=><li key={u.id}>{u.username} · {u.platform_admin?"平台管理员":"成员"} · {u.enabled?"启用":"停用"}<button disabled={busy||u.id===user.id} onClick={()=>void run(async()=>{await api(`/enterprise/users/${u.id}`,"PATCH",{version:u.version,enabled:!u.enabled});await refresh(user)})}>{u.enabled?"停用用户":"启用用户"}</button></li>)}</ul><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api("/enterprise/users","POST",{username:newUser,password:newPassword,platform_admin:platformAdmin});setNewUser("");setNewPassword("");setPlatformAdmin(false);await refresh(user)})}}><label>新用户名<input autoComplete="off" required value={newUser} onChange={e=>setNewUser(e.target.value)}/></label><label>初始密码<input type="password" autoComplete="new-password" minLength={12} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label><input type="checkbox" checked={platformAdmin} onChange={e=>setPlatformAdmin(e.target.checked)}/>平台管理员</label><button disabled={busy}>创建用户</button></form></section>
 <section><h2>分配成员</h2><label>租户<select aria-label="租户" value={selectedTenant} onChange={e=>setSelectedTenant(e.target.value)}><option value="">选择租户</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>用户<select aria-label="用户" value={selectedUser} onChange={e=>setSelectedUser(e.target.value)}><option value="">选择用户</option>{users.filter(u=>!u.platform_admin).map(u=><option key={u.id} value={u.id}>{u.username}</option>)}</select></label><label>角色<select aria-label="角色" value={role} onChange={e=>setRole(e.target.value)}><option value="viewer">查看者</option><option value="tenant_admin">租户管理员</option></select></label><button disabled={busy||version===null} onClick={()=>void run(async()=>{const v=await api(`/enterprise/tenants/${selectedTenant}/members/${selectedUser}`,"PUT",{role,version});setVersion(v.version);setNotice("成员权限已保存。");await refresh(user)})}>保存成员</button><button disabled={busy||!version} onClick={()=>void run(async()=>{await api(`/enterprise/tenants/${selectedTenant}/members/${selectedUser}`,"DELETE",{version});setVersion(0);setNotice("成员已移除。");await refresh(user)})}>移除成员</button></section>
 <section><h2>企业管理审计</h2><p>最近100条，仅保存操作和实体标识。</p><ul>{audit.map(a=><li key={a.id}>{a.created_at} · {a.action} · {a.actor_id} · {a.entity_id}</li>)}</ul></section></>}
 {tenantID&&!tenant&&<p role="alert">没有此租户的访问权限。</p>}{tenant&&!tenant.enabled&&<p role="alert">租户已停用。</p>}
 {tenant?.enabled&&tenant.role==="viewer"&&<section><h2>只读用量报表</h2><button disabled={busy} onClick={()=>void run(()=>refresh(user))}>刷新报表</button>{report&&<><p>请求 {report.usage.requests} · 已知输入 {report.usage.known_input_tokens} · 已知输出 {report.usage.known_output_tokens} · 未知费用请求 {report.usage.cost_unknown_requests}</p><p>{report.usage.notice}</p><h3>预算</h3>{report.budgets.length===0?<p>尚无预算。</p>:<ul>{report.budgets.map((b:any)=><li key={b.id}>{b.name} · {b.currency} · 上限 {b.amount_limit} · 可用 {b.available}</li>)}</ul>}<h3>最近请求</h3>{report.requests.length===0?<p>尚无请求。</p>:<table><thead><tr><th>时间</th><th>模型</th><th>状态</th><th>用量完整性</th></tr></thead><tbody>{report.requests.map((r:any)=><tr key={r.id}><td>{r.started_at}</td><td>{r.requested_model}</td><td>{r.status}</td><td>{r.usage_completeness}</td></tr>)}</tbody></table>}</>}</section>}
 </section>{tenant?.enabled&&tenant.role==="tenant_admin"&&renderAdmin()}</>;
}
